---
- hosts: all
  tasks:

    - name: install packages
      yum: name={{ item }} update_cache=yes state=latest
      loop:
        - python
        - git
        - python-pip
        - supervisor

    - name: install pip packages
      pip: 
        name: "{{ item }}"
      loop:
        - flask
        - supervisor

    - name: Create app directory
      file:
        name: /tmp/myapp
        state: directory
        mode: 0755 

    - name: Copy flask app
      template: src=hello.py dest=/tmp/myapp/hello.py
              
    - name: configure supervisor
      template: src=myapp.conf dest=/etc/supervisord.d/myapp.conf
      notify:
        - restart supervisor
  
  handlers:
    - name: restart supervisor
      supervisorctl: name=myapp state=started
